var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   o              xxx           ",
   "                                                   xx   y        xx!!xx         ",
   "                 o                   o o      xx xx  xx           x!!!x         ",
   "                   xxx                      x         xxxx       xx!xx          ",
   "       xx   xxx y                 y   xxxxx  x             x      xvx           ",
   "                       xx                                                  xx   ",
   "  xx                             xxx            o o          xxx             x  ",
   "  x     xxx   y         o     xx     !!!!                       y            x  ",
   "  x                                      xxxxxxxx     y                    o x  ",
   "  x          xxxx       o       y                        xxxx                x  ",
   "  x  @       x  xx!!!!xxx            xxx                       y      xxxxxxxx  ",
   "  xxxxxxx!!xxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxx     xxxxx   xxxxxxxxxxxxx        ",
   "        x!!x                  x!!!x          x!!v!!x   x     x                  ",
   "        xxxx                  x!!!x          x!!!!!x   x!!!!!x                  ",
   "                              x!!!x          x!!!!!x   x!!!!!x                  ",
   "                              xxxxx          xxxxxxx   xxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                         v        ",
   "                            x                                                                                     ",
   "                       x    x      x                                                                              ",
   "                     xx     x      xxxxxxxxxxxxxxxxxxxxxxx                                                        ",
   "                   xx       x      x                    x                                                         ",
   "                    x          o   x                  xxx             x!!x                                        ",
   "               xx!!!xx        xxx   x                x                x   x                xxxxxxx!!!xxxx xxxx    ", 
   "              xxx!!!x     x         x  o             x   xxxxxxxx!xxxxx     x  xxxxxxxxxxxxxx                x    ",
   "             xxxx!!!x    xx   !    xxxx          o   xxxx                   xxxx                             x    ",
   "     @    xxxxxxx!!!  o x         xxxx  o      o                                                 o           x    ",
   "    xxx      x   xxxxxxxxxxx        x!!!xx  xxxx             x                        xxxxx    xxxxxx       xx    ",
   "    x x      x         x    x   o xx !!!!!!!!!!!  xx     xxxxx      o            o        xx               o x    ",
   "!!!!x x!!!!!!x         x!!! x    x!!x!!xx!!!!!!x      xxx!!!!!!     x     =     xxx                      xxxxx    ",
   "!!!!x x!!!!!!x         x!!!xx       xxxxxxxxxx     xx!!!!!!xx!xxxxxxxxxxxxxxx!!xx xx    o  xx        y xxx        ",
   "!!!!x x!!!!!!x         x!!!!!xxx  o              xxxxx!!!!!!xx                    xx   o xx             x         ",
   "!!!!x x!!!!!!x         x!!!!!x             o       xx!!!!!!xx                       xxxxxxxx xxxxxx!!!!!!x        ",
   "!!!!x x!!!!!!x         x!!!!!xxxxx     xxxxxxxxxxxxxx!!!!!!xx                                     x!!!!!!x        ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                       xxxxxxxx        ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                           v                             v                    ",
   "                                                                   v                                          ",
   "                                                                                   v                          ",
   "                                                                        v       v                             ",
   "          v           v       v            v                               v                                  ",
   "                                                       oo                                                     ",
   "                                                        xxx                                  =                 ",
   "                                                     xxx   x                                                  ",
   "                                                    x       x                                                 ",
   "              =                                    x         xo                                     =         ",
   "                                                 xx           x                       v                       ",
   "   =                                            x!              x                                             ",
   "  |                                         oxx                 x                                             ",
   "      =                                   xxx                    !!!  o                                       ",
   "    |                                     x!x                       vxxxx                            =        ",
   "    =                             o   xx                               x     i                                 ",
   "  |                               xxxxxxxxxxxxx                        x    xx                                ",
   "  |                          oxxxx   v   v    x                        x                                      ",
   "                             xxx                x                        x   xxxxxx                  xx       ",
   "                    xxxx!!!xxx                 x                        x         xx               =  x       ",
   "                   x      v                    x                        x!!!!!!!                     x        ",
   "             oxxxxx                            x                        x!!!!!!!                     x        ",
   "            xx                                 x                        x!!!!!!!    o o o o o o o   ox        ",
   "          xx                                   x                        x!!!!!!!xxxxxxxxxxxxxxxxxxxxxx        ",
   "       oxx                                     x                                                              ",
   "                o                              x                                                              ",
   "                x                              x                                                              ",
   "               x x                             x                                                              ",
   "   xxx     o    x   x            o o o           x                                                            ",
   "    x!!!xxxx!!!x  xxxxxxxxxxxxxxxxxxxxxxxxxx   x                                                              ",
   "    x!!!!!!!!!!x                              x                                                               ",
   "    x!!!!!!!!!!x                             x                                                                ",
   "    xxxxxxxxxxx                          xxxx                                                                 ",
   "   x                                    x                                                                     ",
   "   x                                  xx                                                                      ",
   "   x                                xx                                                                        ",
   "   x                       xxxx!!!xx                                                                          ",
   "   x                      x                                                                                   ",
   "   x                     x                                                                                    ",
   "   x                 xxxx                                                                                     ",
   "   x             xxxx                                                                                         ",
   "   x         xxxx                                                                                             ",
   "   x     @  x                                                                                                 ",
   "   xxxxxxxxxx                                                                                                 "],
  ["                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                       @                                                                                       ",
   "        xx             xx          xxxxxxxxxx         xx               xx                                      ",
   "          x           x           x          x          x             x                                        ",
   "           x         x           x            x         x             x                                        ",
   "            x       x            x            x         x             x                                        ",
   "             x     x             x            x         x             x                                        ",
   "              x   x              x            x         x             x                                        ",
   "               x x               x            x         x             x                                        ",
   "                x                x            x         x             x                                        ",
   "                x                x            x         x             x                                        ",
   "                x                x            x         x             x                                        ",
   "                x                x            x         x             x                                        ",
   "                x                x            x         x             x                                        ",
   "                x                 x          x           x           x                                         ",
   "                x                  xxxxxxxxxx             xxxxxxxxxxx                                          ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "        x                         x     xxxxxxxxxxxxxxx      x         x        x                              ",
   "         x                       x             x             x x       x        x                              ",
   "          x                     x              x             x  x      x        x                              ",
   "           x                   x               x             x   x     x        x                              ",
   "            x        x        x                x             x    x    x        x                              ",
   "             x      x x      x                 x             x     x   x        x        o       o             ",
   "              x    x   x    x                  x             x      x  x        x                        x      ",
   "               x  x     x  x                   x             x       x x             o               o   x      ",
   "                x         x             xxxxxxxxxxxxxxx      x        x         x     o             o    x     ",
   "                                                                                       ooooooooooooo     x      ",
   "                                                                                                         X      ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",                                                                                                  
   "                                                                                                               "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
